name: Tests deployment script

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "*/10 * * * *"
        - cron: "*/20 * * * *"
        - cron: "*/30 * * * *"

env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    test-scrip:
        name: Test script
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              id: setup-node
              with:
                  cache: npm

            - name: Install dependencies
              run: |
                  npm install
            
            - name: Setup FFmpeg
              uses: FedericoCarboni/setup-ffmpeg@v2

            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  name: cache
                  workflow_conclusion: ""
                  if_no_artifact_found: warn

            - name: Run test script
              timeout-minutes: 60
              env:
                  CONFIG: ${{ secrets.CONFIG }}
              run: |
                  npm start

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: cache
                  path: .cache.*
